### PR TITLE
Update to PR#3703: Multiple genome support mutation 

### PR DESCRIPTION
**Pull request by sandertan**
# What? Why?
Hi @khzhu, this PR:
- Restore the database schema for 2.4.1 back to how it is in the current master
- Recreate the database schema in 2.7.0.
- Change `mutation_event` table.
- Modify migrate_db.py, which looks in the database to which reference genome the genes should be linked, or asks the users.
- Update validation for segment files.
- Update validation of `NCBI_Build` column.
- Update tests.
- Update documentation.

I think that if you think this PR is ok, we can merge it in your branch, and continue the conversation in https://github.com/cBioPortal/cbioportal/pull/3703/

### CODE REVIEW

**Comment by khzhu** [comment]
Hi @sandertan , 
1. Missing update 2.4.0 statement would only result in reference_genome and reference_genome_gene tables be created undesirably, but there is no harm, since two tables have not been in use, but why you need to remove two tables if already exist? 

2. checkNCBIbuild method is not right, since it always returns true, should change 
from
```
def checkNCBIbuild(self, value):
-        return value in (self.portal.genome_build[self.portal.species].values()[0])
+        if value not in REFERENCE_GENOME_DICT[self.portal.species]:
+            self.logger.error('Value in NCBI_Build is not supported. '
+                              'Expected hg19, hg38, mm10, GRCh37, GRCh38 or GRCm38.',
+                              extra={'line_number': self.line_number,
+                                     'column_number': self.cols.index('NCBI_Build'),
+                                     'cause': value})
+        return True
```
to 
```
def checkNCBIbuild(self, value):
-        return value in (self.portal.genome_build[self.portal.species].values()[0])
+        if value not in REFERENCE_GENOME_DICT[self.portal.species]:
+            self.logger.error('Value in NCBI_Build is not supported. '
+                              'Expected hg19, hg38, mm10, GRCh37, GRCh38 or GRCm38.',
+                              extra={'line_number': self.line_number,
+                                     'column_number': self.cols.index('NCBI_Build'),
+                                     'cause': value})
               return False
          else:
+             return True
```

**Comment by sandertan** [comment]
Hi @khzhu ,

1a. `Missing update 2.4.0 statement ` What do you mean? This is about 2.4.1

1b. So the update to the schema for 2.4.1 was in RC and is now in Master, which means it has been released. If we would like to edit something in the tables created in 2.4.1, we have to do this in a **new** release. One way of doing this is indeed keeping and modifying the tables. However, the `reference_genome_gene` gene table is now incorrectly filled because of

```
.......SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(gene.CYTOBAND,IF(LOCATE('p', gene.CYTOBAND), 'p', 'q'), 1),'q',1),'cen',1),1........
```

We could empty the table, modify the schema, and fill it again. But as you said, the tables are not used yet. Therefore I think it is easier, and more easy to read for others, if we remove the tables, and recreate them with the correct statements. 

2. I think it is correct, because it logs an error with `self.logger.error`. The `True / False` this function can return, is only used by another method that defines errors, but I'm not using that. I prefer logging the error in the method itself. I tested my method with a unit test, and manually:
screen shot 2018-03-26 at 11 12 28

3. So from the CircleCI report, I noticed the test for the API is failing. Because I changed the table to have both ENTREZ_GENE_ID and REFERENCE_GENOME_ID as foreign key, I think the insert statement in testSql.sql fails. Do you know a way to solve this?

**Comment by khzhu** [comment]
@sandertan , 
1. there is nothing wrong with the schema definitions why you need to truncate the tables than recreated them, it will confuse users. All you need is to update reference_genome_id in the reference_genome_gene table by a select statement. Please see attached git diff screenshots)
screen shot 2018-03-26 at 10 32 29 am

2. you are logging the error not raising the error, so your last statement of "Return True" will be executed.

**Comment by sandertan** [comment]
Hi @khzhu .

1. Perhaps you can cherry-pick this commit to your branch, and update the sql code with your proposed solution. Then we can continue the discussion there.

2. It's fine to return true, I also do not want to raise an error. I just want to log the error in the validation report.

**Comment by sandertan** [comment]
Hi Kelsey. The reason I truncate the table and then recreate it is because genes are already linked. If a user with hg38 upgraded to cBioPortal 1.12.1, his genes are now linked to hg19. By truncating, recreating the table and using the update migration wrapper, the table should be correctly filled.

Could you rebase your branch on RC?

**Comment by khzhu** [comment]
Hi @sandertan , I understand that, but there is a better way to fix that, since before 1.2.1 only one genome build per instance, so we could simply correct reference_genome_ids (for hg38) using a update sql statement. I do not have time to work on the PR till Thursday, will cherry-pick up your commits then go from there. Thanks!

**Comment by sandertan** [comment]
I think we can close this one, right @khzhu ? You can keep it open if you want to keep it as a reference.

**Pull request closed without merging**
